repos:
- repo: https://github.com/semgrep/pre-commit
  rev: 'v1.118.0'
  hooks:
    - id: semgrep
      entry: semgrep
      # Replace <SEMGREP_RULESET_URL> with your custom rule source
      # or see https://semgrep.dev/explore to select a ruleset and copy its URL
      # args: ['--config',  'p/javascript-typescript' , '--error', '--skip-unknown-extensions']
      args:
          - '--config'
          - 'p/typescript'
          - '--config'
          - 'p/react'
          - '--config'
          - 'p/owasp-top-ten'
          - '--error'
          - '--skip-unknown-extensions'
        
- repo: local
  hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --results=verified,unknown --fail'
        # For running trufflehog in docker, use the following entry instead:
        # entry: bash -c 'docker run --rm -v "$(pwd):/workdir" -i --rm trufflesecurity/trufflehog:latest git file:///workdir --since-commit HEAD --results=verified,unknown --fail'
        language: system
        stages: ["commit", "push"]