name: Qlty Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  security-events: write
  issues: write
  pull-requests: write

jobs:
  qlty-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Get full history

      - name: Install Qlty CLI
        run: |
          curl -sSL https://qlty.sh | bash -
          echo "$HOME/.qlty/bin" >> $GITHUB_PATH

      - name: Install jq for JSON processing
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run Qlty Check and Export SARIF
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NO_COLOR: true
        run: |
          qlty install
          qlty check --all --sarif > qlty-results.sarif || true

      - name: Clean SARIF for GitHub Upload
        run: |
          jq 'del(.runs[].tool.driver.notifications) | del(.runs[].automationDetails)' qlty-results.sarif > cleaned-results.sarif

      - name: Upload cleaned SARIF to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: cleaned-results.sarif
          category: qlty-${{ github.run_id }}-${{ github.job }}

      - name: Upload SARIF as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: qlty-sarif-report
          path: cleaned-results.sarif
