name: semgrep

on:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write
  issues: write
  pull-requests: write

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep and save report
        run: semgrep scan \
            --config=auto \
            --config=.semgrep/custom.yml \
            --metrics=off \
            --sarif \
            --output=semgrep-results.sarif || true

    

      - name: Upload Semgrep report artifact
        uses: actions/upload-artifact@v4
        with:
            name: semgrep-report
            path: semgrep-report.json
      - name: Upload SARIF to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
            sarif_file: semgrep-results.sarif

  